name: "workflow de mise en production"  
on: 
  workflow_dispatch: 
    inputs:
      server:
        description: 'Environnement à utiliser'
        required: true
        default: 'dev'
jobs:
  deploy-env:
    runs-on: Ubuntu-latest
    steps:
      - name: Start workflow
        run: echo 'worflow démarré sur ${{ github.ref }}'
      - name: Checkout
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4.1.1 
      - name: Prod deploy
        if: ${{ github.event.inputs.server == 'prod' }}
        run: echo "PROD"
      - name: Qualif deploy
        if: ${{ github.event.inputs.server == 'qual' }}
        run: echo "QUALIF" 
             exit 1 
      - name: Dev deploy
        if: ${{ github.event.inputs.server == 'dev' }}
        run: echo "DEV"
      - name: End workflow
        run: echo "End workflow"
